[build]
  base = "frontend/"
  command = "CI=false node node_modules/react-scripts/bin/react-scripts.js build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "/api"
  ESLINT_NO_DEV_ERRORS = "true"

[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "https://invoice-system-backend.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
