[build]
  base = "frontend/"
  command = "node build-netlify.js"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://rsw-invoice-system.onrender.com/api/v1"

[[redirects]]
  from = "/api/*"
  to = "https://rsw-invoice-system.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
